### ISSUE TITLE
How did you lose your star counts?

### ISSUE THREAD

**Issue by Glup3** [damnitharshit/wallpapers#1]
Hey! Random stranger here 😅 

I am currently working on a tool that checks for star histories and my program gave me some strange errors. I checked and noticed that your repository previously had 260 stars. I am just wondering what happened 😅 

PS: nice looking wallpapers 😄

**Comment by damnitharshit** [comment]
Hello! 👋

You are right, this repo used to have 260 stars. 

Recently, It just so happened that I had to change devices and while moving my stuff around I noticed that this repo had become impossible to clone because of its huge size. This bugged me a lot, and after a while I just ended up deleting the published repo and restarting with a fresh one, thereby losing all the stars. 

PS: Thanks!

**Comment by Glup3** [comment]
Ahhh I see, thats unfortunate.
Thanks for clarifying and I wish you the best!
